### ISSUE TITLE
Using IMAP mode

### ISSUE THREAD

**Issue by ckampi** [debricked/dmarc-visualizer#23]
Hello, I'm trying to use IMAP to read emails directly from inbox, I had change the parsedmarc.ini file:

[general]
save_aggregate = True
save_forensic = True
output = /output/

[imap]
host = (my value)
port = 993
user = (my value)
password = (my value)
watch = True
reports_folder = INBOX

[elasticsearch]
hosts = elasticsearch:9200
ssl = False

Do I need to change something more?, maybe something at docker-compose.yml ?

Thank you for your help!!

**Comment by lil-S** [comment]
Hi
Update the docker-compose.yml file as shown below and you should be good to go.
```
version: '3.5'
services:
  parsedmarc:
    build: ./parsedmarc/
    volumes:
      - ./parsedmarc/parsedmarc.ini:/parsedmarc.ini:ro
      - ./output_files:/output
    command: parsedmarc -c /parsedmarc.ini
    depends_on:
      - elasticsearch
    restart: on-failure

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.1
    environment:
      - discovery.type=single-node

  grafana:
    build: ./grafana/
    ports:
      - 3000:3000
    user: root
    environment:
      GF_INSTALL_PLUGINS: grafana-piechart-panel,grafana-worldmap-panel
      GF_AUTH_ANONYMOUS_ENABLED: 'true'
```
