### ISSUE TITLE
Persistance?

### ISSUE THREAD

**Issue by kdomke** [debricked/dmarc-visualizer#26]
Maybe I am stupid, but every time I restart this, I get an empty database. 

Where do I have to add a volume to not loose my data?

**Comment by lasat** [comment]
You should add a volume to elasticsearch: docker-compose.override.yml
```
version: '3.5'
services:
  elasticsearch:
    volumes:
      - ./data/es:/usr/share/elasticsearch/data
```
